title: Ansh's Portfolio 
description: "A portfolio showcasing my work and projects."
owner_name: Ansh Kumar
github_username: magic005
github_repo: "student_ansh_test" 
baseurl: "/student_ansh_test"
future: true

remote_theme: jekyll/minima
# remote_theme: pages-themes/minimal@v0.2.0


minima:
  nav_pages:
    - navigation/lessons.md
    - navigation/blog.md
    - navigation/search.md
    - navigation/about.md
    - navigation/docs.md
    - navigation/hacks/leaderboard.md
    - navigation/checklist.md
    - navigation/resource.md
    - navigation/authentication/login.md
    - navigation/authentication/logout.md


  # for partia themes, uncomment the following line and add the theme name, otherwise leave blank/commented and update sass
  # skin: 
  
  social_links:
    - { platform: github, user_url: "https://github.com/Open-Coding-Society"}
    - { platform: x, user_url: "https://x.com/Open_Coding" }
    - { platform: youtube, user_url: "https://www.youtube.com/@OpenCodingSociety" } 

plugins:
  - jekyll-remote-theme